theme: jekyll-theme-leap-day

title: XivRUS (alpha)
description: Неофициальная русская локализация FINAL FANTASY XIV
locale: ru-RU
show_downloads: true

kramdown:
  input: GFM
  auto_ids: true
  transliterated_header_ids: true
  parse_block_html: true

github:
  rus_url: https://github.com/endervad/ffxiv_translation/releases/download/v0.5.4/RUS-0.5.4-2022-09-14.ttmp2
  ruen_url: https://github.com/endervad/ffxiv_translation/releases/download/v0.5.4/RUEN-0.5.4-2022-09-14.ttmp2
